CREATE USER 'library'@'localhost' IDENTIFIED BY 'lib';
GRANT USAGE ON *.* TO 'library'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `library`;
GRANT ALL PRIVILEGES ON `library`.* TO 'library'@'localhost';